system = "x86_64-linux" # Architecture to target
serial = ""             # Motherboard serial number

hostname = "lachesis" # The hostname for the device
# profile = ""        # System configuration to use (hostname, by default)
user = "shane"        # The home and configs to import