# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1711492352);
user_pref("app.update.lastUpdateTime.background-update-timer", 1711492540);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1711492489);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1711492112);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1711492232);
user_pref("app.update.lastUpdateTime.user-agent-updates-timer", 1711492660);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 27);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.slowStartup.averageTime", 1061);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20240126000616");
user_pref("browser.startup.homepage_override.mstone", "6.6.0");
user_pref("browser.startup.page", 0);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"palefill@addons.martoks-place.de\":{\"version\":\"1.28\",\"type\":\"extension\",\"descriptor\":\"/home/shane/.moonchild productions/pale moon/5ljudcj9.default/extensions/palefill@addons.martoks-place.de.xpi\",\"multiprocessCompatible\":false},\"uBlock0@raymondhill.net\":{\"version\":\"1.16.4.30\",\"type\":\"extension\",\"descriptor\":\"/home/shane/.moonchild productions/pale moon/5ljudcj9.default/extensions/uBlock0@raymondhill.net.xpi\",\"multiprocessCompatible\":false}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B2C646A52-4EDC-455F-8047-9405795D3E51%7D:7.3.1");
user_pref("extensions.lastAppVersion", "33.0.0");
user_pref("extensions.lastPlatformVersion", "6.6.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.ublock0.cloudStorage.myFiltersPane", "");
user_pref("extensions.ublock0.cloudStorage.myRulesPane", "");
user_pref("extensions.ublock0.cloudStorage.tpFiltersPane", "");
user_pref("extensions.ublock0.cloudStorage.whitelistPane", "");
user_pref("extensions.ublock0.immediateHiddenSettings", "{\"suspendTabsUntilReady\":false,\"userResourcesLocation\":\"unset\"}");
user_pref("extensions.ublock0.legacyToolbarButtonAdded", true);
user_pref("extensions.ublock0.shortcuts.launch-element-picker", "");
user_pref("extensions.ublock0.shortcuts.launch-element-zapper", "");
user_pref("extensions.ublock0.shortcuts.launch-logger", "");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://discover/");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.xpiState", "{\"app-profile\":{\"{2C646A52-4EDC-455F-8047-9405795D3E51}\":{\"d\":\"/home/shane/.moonchild productions/pale moon/5ljudcj9.default/extensions/{2C646A52-4EDC-455F-8047-9405795D3E51}.xpi\",\"e\":true,\"v\":\"7.3.1\",\"st\":1711492510000},\"palefill@addons.martoks-place.de\":{\"d\":\"/home/shane/.moonchild productions/pale moon/5ljudcj9.default/extensions/palefill@addons.martoks-place.de.xpi\",\"e\":true,\"v\":\"1.28\",\"st\":1711492309000},\"uBlock0@raymondhill.net\":{\"d\":\"/home/shane/.moonchild productions/pale moon/5ljudcj9.default/extensions/uBlock0@raymondhill.net.xpi\",\"e\":true,\"v\":\"1.16.4.30\",\"st\":1711492439000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/nix/store/gx94gwgp2gs8xkqkiydq0j9l38c6mxhf-palemoon-bin-33.0.0/lib/palemoon/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":false,\"v\":\"33.0.0\",\"st\":1000}}}");
user_pref("general.skins.selectedSkin", "moonscape-classic");
user_pref("general.useragent.updates.lastupdated", "1711492661040");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_current_max_pages", 122334);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("services.sync.prefs.sync.extensions.ublock0.cloudStorage.myFiltersPane", true);
user_pref("services.sync.prefs.sync.extensions.ublock0.cloudStorage.myRulesPane", true);
user_pref("services.sync.prefs.sync.extensions.ublock0.cloudStorage.tpFiltersPane", true);
user_pref("services.sync.prefs.sync.extensions.ublock0.cloudStorage.whitelistPane", true);
user_pref("signon.importedFromSqlite", true);
user_pref("status4evar.firstRun", false);
user_pref("status4evar.migration", 8);
user_pref("toolkit.startup.last_success", 1711492978);
