cargo-features = ["profile-rustflags"]

[package]
name = "shanetrs_pm"
version = "0.1.0"
edition = "2021"

[lib]
name = "shanetrs_pm"
path = "src/lib.rs"
proc-macro = true

[[bin]]
name = "test"
path = "src/test.rs"

[profile.dev]
# rustflags = ["-Zmacro-backtrace"]

[profile.release]
strip = true
opt-level = "z"
codegen-units = 1
lto = true
panic = "abort"
# rustflags = ["-Zlocation-detail=none"]

[dependencies]
syn = { version = "2.0.48", features = ["full"] }
quote = "1.0.35"
proc-macro2 = "1.0.78"
shanetrs = { path = "../shanetrs" }
