#!/usr/bin/env bash
cd "$(dirname "$0")" || exit

[ -f "$PWD/last" ] && while read -r FILE; do
    FILE="${FILE#*/}" # Strip target user
    FILE="${FILE#*/}" # Strip target profile
    [ -L "$HOME/$FILE" ] && # Only remove symlinks
        rm "$HOME/$FILE"
done < "$PWD/last"
echo -n > "$PWD/last" # Wipe list

printf "Recursively linking the following directories:\n  %s\n" "$*"
for i in "$@"; do
    find "$i" -type f >> last
done

[ -f "$PWD/last" ] && while read -r FILE; do
    TARGET="$(realpath "$FILE")"
    FILE="${FILE#*/}" # Strip target user
    FILE="${FILE#*/}" # Strip target profile"
    if [ ! -L "$HOME/$FILE" ]; then
        mkdir -p "$HOME/$(dirname "$FILE")"
        ln -sf "$TARGET" "$HOME/$FILE" # Replace existing files
    fi
done < "$PWD/last"
echo This should be replaced via systematic home-manager symlinks