cargo-features = ["profile-rustflags"]
# workspace = { members = ["shanetrs_pm"] }

[package]
name = "server_tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "aio"
path = "src/main.rs"

[profile.dev]
# rustflags = ["-Zmacro-backtrace"]

[profile.release]
strip = true
opt-level = "z"
codegen-units = 1
lto = true
panic = "abort"
# rustflags = ["-Zlocation-detail=none"]

[dependencies]
tokio = { version = "1.35.1", features = [
    "rt-multi-thread",
    "net",
    "io-util",
    "time",
    "macros",
] }
shanetrs_pm = { path = "../shanetrs_pm" }
shanetrs = { path = "../shanetrs" }
